server:
  port: 8080

spring:
  application:
    name: polizas-service
  profiles:
    active: default
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-db:3306/polizas_db
    username: appuser
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
